-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 23:45:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `email_address` VARCHAR(45) NULL DEFAULT NULL,
  `roles` BIT(4) NOT NULL COMMENT 'BIT 0: admin\\nBIT 1: editor\\nBIT 2: reviewer\\nBIT 3: author',
  `school_id` INT(8) UNSIGNED NULL DEFAULT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `institution` VARCHAR(45) NULL DEFAULT NULL,
  `date_joined` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`journal` (
  `id_number` INT(10) NOT NULL,
  `name` VARCHAR(255) NULL,
  `institution` VARCHAR(32) NOT NULL,
  `editor` VARCHAR(32) NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_number`),
  INDEX `editor` (`editor` ASC) VISIBLE,
  CONSTRAINT `editor`
    FOREIGN KEY (`editor`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE SET NULL
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table `mydb`.`paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paper` (
  `paper_id` INT(10) NOT NULL,
  `author` VARCHAR(32) NULL DEFAULT NULL,
  `file` BLOB NULL DEFAULT NULL,
  `version` INT(10) UNSIGNED NULL DEFAULT NULL,
  `upload_date` DATE NULL DEFAULT NULL,
  `journal_id` INT(10) NULL,
  PRIMARY KEY (`paper_id`),
  INDEX `user` (`author` ASC) VISIBLE,
  INDEX `journal` (`journal_id` ASC) VISIBLE,
  CONSTRAINT `user`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`username`)
    ON UPDATE CASCADE,
  CONSTRAINT `journal`
    FOREIGN KEY (`journal_id`)
    REFERENCES `mydb`.`journal` (`id_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`proposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proposal` (
  `proposal_id` INT(10) NOT NULL,
  `paper_submission_author` INT(10) NULL DEFAULT NULL,
  `paper_submission_reviewer` INT(10) NULL DEFAULT NULL,
  `author` VARCHAR(32) NOT NULL,
  `reviewer1` VARCHAR(32) NULL DEFAULT NULL,
  `reviewer2` VARCHAR(32) NULL DEFAULT NULL,
  `reviewer3` VARCHAR(32) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `due_date` DATE NULL,
  `upload_date` DATE NULL,
  PRIMARY KEY (`proposal_id`),
  INDEX `paper` (`paper_submission_author` ASC, `paper_submission_reviewer` ASC) VISIBLE,
  INDEX `paper_reviewer` (`paper_submission_reviewer` ASC) VISIBLE,
  INDEX `author` (`author` ASC) VISIBLE,
  INDEX `reviewer1` (`reviewer1` ASC) VISIBLE,
  INDEX `reviewer3` (`reviewer3` ASC) VISIBLE,
  INDEX `reviewer2` (`reviewer2` ASC) VISIBLE,
  CONSTRAINT `author`
    FOREIGN KEY (`author`)
    REFERENCES `mydb`.`user` (`username`)
    ON UPDATE CASCADE,
  CONSTRAINT `paper_author`
    FOREIGN KEY (`paper_submission_author`)
    REFERENCES `mydb`.`paper` (`paper_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `paper_reviewer`
    FOREIGN KEY (`paper_submission_reviewer`)
    REFERENCES `mydb`.`paper` (`paper_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `reviewer1`
    FOREIGN KEY (`reviewer1`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `reviewer2`
    FOREIGN KEY (`reviewer2`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `reviewer3`
    FOREIGN KEY (`reviewer3`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `proposal_id` INT(11) NOT NULL,
  `comment_text` MEDIUMTEXT NULL DEFAULT NULL,
  `reviewer_username` VARCHAR(32) NULL DEFAULT NULL,
  `paper_version` INT(10) NULL DEFAULT NULL COMMENT 'the version of the paper that the comment belongs to',
  INDEX `proposal_id` (`proposal_id` ASC) VISIBLE,
  INDEX `user` USING BTREE (`reviewer_username`) VISIBLE,
  CONSTRAINT `proposal_id`
    FOREIGN KEY (`proposal_id`)
    REFERENCES `mydb`.`proposal` (`proposal_id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
