# Generated by Django 3.0.3 on 2020-03-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField(max_length=50)),
                ('author', models.CharField(max_length=500)),
                ('file', models.FileField(upload_to='file/pdfs/')),
            ],
            options={
                'db_table': 'paper',
                'managed': False,
            },
        ),
    ]
