# Generated by Django 3.0.3 on 2020-03-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
