# Generated by Django 3.0.4 on 2020-04-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0002_delete_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('file', models.FileField(upload_to='')),
                ('STATUS_OF_PAPER', models.CharField(choices=[('SUB', 'Submitted'), ('REV', 'Reviewed'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='SUB', max_length=3)),
            ],
        ),
    ]
