# Generated by Django 3.0.3 on 2020-03-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=45, null=True)),
                ('email_address', models.CharField(blank=True, max_length=45, null=True)),
                ('roles', models.BinaryField()),
                ('school_id', models.PositiveIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('institution', models.CharField(blank=True, max_length=45, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
