# Generated by Django 3.0.4 on 2020-04-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('reviewer', models.CharField(max_length=250)),
                ('editor', models.CharField(max_length=250)),
                ('adm', models.CharField(max_length=250)),
            ],
        ),
    ]
