# Generated by Django 3.0.4 on 2020-04-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.IntegerField(max_length=10)),
                ('status', models.TextField(max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_author', to='home.User')),
                ('reviewer_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_reviewer_1', to='home.User')),
                ('reviewer_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_reviewer_2', to='home.User')),
                ('reviewer_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_reviewer_3', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField(max_length=10)),
                ('version', models.IntegerField(max_length=10)),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_author', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.IntegerField(max_length=10)),
                ('name', models.TextField(max_length=100)),
                ('institution', models.TextField(max_length=100)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_editor', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(max_length=20)),
                ('paper_version', models.IntegerField(max_length=10)),
                ('text', models.TextField(max_length=500)),
                ('proposal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_proposal_id', to='userPages.Proposal')),
                ('reviewer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reviewer', to='home.User')),
            ],
        ),
    ]
