# Generated by Django 3.0.4 on 2020-04-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_institution', to='userPages.Institution'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='version',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
