# Generated by Django 3.0.4 on 2020-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='abstract',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
