# Generated by Django 3.0.4 on 2020-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='author_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewer_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
