# Generated by Django 3.0.4 on 2020-04-09 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='reviewer_file',
            new_name='reviewer_1_file',
        ),
        migrations.AddField(
            model_name='proposal',
            name='abstract',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewer_2_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewer_3_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.TextField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 21, 35, 5, 982247, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
