# Generated by Django 3.0.4 on 2020-04-12 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 20, 40, 38, 561105, tzinfo=utc)),
        ),
    ]
