# Generated by Django 3.0.4 on 2020-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0002_auto_20200403_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=200)),
            ],
        ),
    ]
