# Generated by Django 3.0.4 on 2020-04-12 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0002_auto_20200412_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 20, 40, 49, 664456, tzinfo=utc)),
        ),
    ]
