# Generated by Django 3.0.4 on 2020-04-09 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0003_auto_20200409_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.TextField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 21, 0, 11, 667208, tzinfo=utc)),
        ),
    ]
