# Generated by Django 3.0.4 on 2020-04-12 20:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0004_auto_20200412_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='editor_comments',
            field=models.TextField(default='none', max_length=12000, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 20, 45, 20, 437592, tzinfo=utc)),
        ),
    ]
