# Generated by Django 3.0.4 on 2020-04-13 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0005_auto_20200412_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='author_resubmit',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='version',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
