# Generated by Django 3.0.4 on 2020-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0006_auto_20200412_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reviewer_1_comment',
            field=models.TextField(default='none', max_length=12000, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewer_2_comment',
            field=models.TextField(default='none', max_length=12000, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewer_3_comment',
            field=models.TextField(default='none', max_length=12000, null=True),
        ),
    ]
