# Generated by Django 3.0.4 on 2020-04-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userPages', '0008_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
